DATABASE time_oltp;

DELETE FROM project_worker WHERE project_id >= 1000000;
DELETE FROM project_manager WHERE project_id >= 1000000;
DELETE FROM user_account WHERE user_account_id >= 1000000;
DELETE FROM client_project WHERE project_id >= 1000000 and project_id NOT IN (70015983, 70015984);
DELETE FROM project WHERE project_id >= 1000000 and project_id NOT IN (70015983, 70015984);
DELETE FROM client WHERE client_id >= 1000000 AND client_id <> 70014096;
DELETE FROM payment_terms WHERE payment_terms_id >= 1000000;
DELETE FROM company WHERE company_id >= 1000000;

DATABASE tcs_catalog;

TRUNCATE late_deliverable;
TRUNCATE rboard_application;
TRUNCATE component_inquiry;
TRUNCATE user_rating;
TRUNCATE copilot_project;
TRUNCATE copilot_profile;
TRUNCATE review_item_comment;
TRUNCATE review_item;
TRUNCATE review_comment;
TRUNCATE review;
TRUNCATE screening_task;
TRUNCATE resource_submission;
TRUNCATE submission;
TRUNCATE upload;
TRUNCATE resource_info;
TRUNCATE resource;
TRUNCATE phase_dependency;
TRUNCATE phase_criteria;
TRUNCATE project_phase_audit;
TRUNCATE project_phase;
TRUNCATE project_info_audit;
TRUNCATE project_info;
TRUNCATE project_audit;
TRUNCATE project_result;
TRUNCATE notification;
TRUNCATE project_spec;
TRUNCATE project_user_audit;
TRUNCATE project_wager;
TRUNCATE linked_project_xref;
TRUNCATE software_competition_pipeline_info;
TRUNCATE contest_sale;
TRUNCATE project;
TRUNCATE comp_client;
TRUNCATE comp_keywords;
TRUNCATE comp_categories;
TRUNCATE comp_technology;
TRUNCATE comp_version_dates;
TRUNCATE comp_version_dates_history;
TRUNCATE comp_jive_category_xref;
TRUNCATE comp_documentation;
TRUNCATE user_role;
TRUNCATE download_tracking;
TRUNCATE comp_versions;
TRUNCATE comp_catalog;

DELETE FROM scorecard_question WHERE scorecard_question_id >= 100 AND scorecard_question_id < 300;
DELETE FROM scorecard_section WHERE scorecard_section_id >= 100 AND scorecard_section_id < 300;
DELETE FROM scorecard_group WHERE scorecard_group_id >= 100 AND scorecard_group_id < 300;
DELETE FROM default_scorecard WHERE scorecard_id >= 100 AND scorecard_id < 300;
DELETE FROM scorecard WHERE scorecard_id >= 100 AND scorecard_id < 300;
DELETE FROM user_permission_grant;
DELETE FROM tc_direct_project;
DELETE FROM user_terms_of_use_xref;
