database informixoltp;

INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (132456, '2001-05-09 01:04:42.000', 'Acknowledge and move on.', '2006-10-06 22:04:54.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (20, '2008-02-15 13:43:53.000', NULL, '2008-02-15 13:43:53.000', NULL, 2, NULL, NULL, NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (21, '2008-02-26 14:40:44.000', NULL, '2008-02-26 14:40:44.000', NULL, 2, NULL, NULL, NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (132457, '2008-07-23 16:09:58.000', 'Do unto your code, as your code would do unto you', '2008-07-23 16:09:58.000', 1, 2, NULL, NULL, NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (132458, '2008-07-23 16:11:03.000', 'carpe noctem', '2008-07-23 16:11:03.000', 1, 2, NULL, NULL, NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124916, '2001-05-09 01:04:42.000', 'test add', '2008-08-13 14:41:19.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124861, '2001-05-09 01:04:42.000', 'User quote', '2008-08-13 14:51:38.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124764, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:05:37.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124772, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:06:59.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124766, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:11:05.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124776, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:12:22.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124834, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:13:00.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124835, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:13:54.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124836, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:14:49.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124852, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:16:01.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124853, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:22:14.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124856, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:22:45.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (124857, '2001-05-09 01:04:42.000', 'User quote', '2008-08-14 14:23:40.000', 1, 2, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244033, '2008-09-19 09:03:17.000', '', '2008-09-19 09:03:17.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244044, '2008-09-22 09:20:42.000', '', '2008-09-22 09:20:42.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244053, '2008-09-22 09:39:44.000', '', '2008-09-22 09:39:44.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244064, '2008-09-22 10:54:14.000', '', '2008-09-22 10:54:14.000', NULL, 1, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244066, '2008-09-22 16:02:17.000', '', '2008-09-22 16:02:17.000', NULL, 1, NULL, '840', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244067, '2008-09-22 16:06:21.000', '', '2008-09-22 16:06:21.000', NULL, 1, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244068, '2008-09-23 13:24:44.000', 'dlkgjdflkgj dlkgj dlkdjgdgdf', '2008-09-23 13:24:44.000', NULL, 2, NULL, '804', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244069, '2008-09-24 14:05:33.000', '', '2008-09-24 14:05:33.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244073, '2008-09-24 14:13:17.000', '', '2008-09-24 14:13:17.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.coder(coder_id,member_since,quote,modify_date,language_id,coder_type_id,date_of_birth,comp_country_code,contact_date) VALUES (27244093, '2008-09-24 14:49:37.000', 'testEmailIP', '2008-09-24 14:49:37.000', NULL, 2, NULL, '008', NULL);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (20, 'Non-Member', 20, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (10, 'Other', 130, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (35, 'News Letter', 35, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (30, 'News Article', 30, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (40, 'Member Referral', 10, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (50, 'Another Web Site', 50, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (6, 'Campus Job Fair', 120, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (60, 'From Faculty', 60, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (70, 'Email from TopCoder', 70, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (80, 'Campus Poster', 80, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (90, 'User Group', 90, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (100, 'Search Engine', 100, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (110, 'IRC/Chat', 110, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (0, 'Decline to Answer', 0, 0);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (120, 'Potential Employer / Recruiter', 125, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (33, 'Magazine Advertisement', 33, 1);
INSERT INTO 'informix'.referral(referral_id,referral_desc,sort,status_id) VALUES (1, 'Unknown', 0, 0);
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244033, 35, NULL, '123');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244044, 110, NULL, 'kljhlk');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244053, 10, NULL, '123132');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244064, 10, NULL, 'kjjlkjh');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244067, 10, NULL, '234324');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244068, 10, NULL, 'sfsfsfsfs');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244069, 10, NULL, 'qrewrew');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244073, 10, NULL, 'wewerf');
INSERT INTO 'informix'.coder_referral(coder_id,referral_id,reference_id,other) VALUES (27244093, 10, NULL, 'dsfsfd');
INSERT INTO 'informix'.current_school(coder_id,school_id,modify_date,gpa,gpa_scale,viewable) VALUES (27244064, 1644, '2008-09-22 10:54:14.000', NULL, NULL, 1);
INSERT INTO 'informix'.current_school(coder_id,school_id,modify_date,gpa,gpa_scale,viewable) VALUES (27244066, 76406, '2008-09-22 16:02:17.000', NULL, NULL, 1);
INSERT INTO 'informix'.current_school(coder_id,school_id,modify_date,gpa,gpa_scale,viewable) VALUES (27244067, 76398, '2008-09-22 16:06:21.000', 1.00, 4.00, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (306, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (317, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (325, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (331, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (342, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (343, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (344, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (345, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (346, 'Are you 18 years of age or older?', 1, 'Age Elligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (385, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (399, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (408, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (415, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (433, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (442, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (451, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (461, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (475, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (483, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (490, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (499, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (510, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (520, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (531, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (547, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (555, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (567, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (580, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (588, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (608, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (620, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (630, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (637, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (648, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (656, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (664, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (673, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (684, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (698, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (701, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (712, 'Are you 18 years of age or older?', 1, 'Age eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (721, 'Are you 18 years of age or older?', 1, 'Are you 18 years', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (731, 'Are you 18 years of age or older?', 1, 'Are you 18 years', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (738, 'Are you 18 years of age or older?', 1, 'Eligibility', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (4122, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (4140, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (4146, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (4165, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (6020, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7393, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7412, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7444, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7312, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7321, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7347, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7359, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7370, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7484, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7487, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7513, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7586, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7790, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7817, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7827, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7924, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (7980, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (8014, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (8034, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16260, 'Are you 18 years of age or older?', 1, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16328, 'How old will you be on February 26, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16335, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16340, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16344, 'How old will you be on March 29, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16358, 'How old will you be on March 15, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16360, 'How old will you be on March 7, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16362, 'How old will you be on March 5, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16370, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16603, 'How old will you be on March 29, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16648, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16670, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16913, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (17243, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (17310, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (17313, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (17340, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (17460, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19030, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19120, 'Are you 18 years of age or older?', 83, 'age', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19254, 'How old will you be on August 18, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19255, 'How old will you be on August 18, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19256, 'How old will you be on August 18, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19257, 'How old will you be on August 18, 2007?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19271, 'How old are you?', 83, 'age', 2, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19411, 'How old will you be on February 5, 2008?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19425, 'How old will you be on January 14, 2008?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19427, 'How old will you be on January 30, 2008?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19429, 'How old will you be on January 14, 2008?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19431, 'How old will you be on February 5, 2008?', 83, 'age', 4, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19272, 'How old will you be on March 16, 2008?', 83, 'agees', 2, 4, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16329, 'Are you enrolled full time at a college or university?', 83, 'incollege', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19258, 'Are you currently or will you be a full time college/university student between July 23, 2007 and November 3, 2007?', 83, 'incollege', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19261, 'Are you currently or will you be a full time college/university student between July 23, 2007 and November 3, 2007?', 83, 'incollege', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19264, 'Are you currently or will you be a full time college/university student between July 23, 2007 and November 3, 2007?', 83, 'incollege', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19267, 'Are you currently or will you be a full time college/university student between July 23, 2007 and November 3, 2007?', 83, 'incollege', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16332, 'Are you enrolled full time at a secondary school (high school)?', 83, 'inhs', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19273, 'Are you currently pursuing or will you be pursuing your secondary school (non-University) education between July 12, 2007 and March 16, 2008?  ,', 83, 'inhs', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (28432, 'Are you currently pursuing or will you be pursuing your secondary school (non-University) education between June 9, 2008 and March 15, 2009?  ,', 83, 'inhs', 2, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16345, 'Which section do you most prefer?', 83, 'pref1', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19412, 'Which section do you most prefer?', 83, 'pref1', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16349, 'Next?', 83, 'pref2', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19416, 'Next?', 83, 'pref2', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (16353, 'Least?', 83, 'pref3', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (19420, 'Least?', 83, 'pref3', 4, 1, 1);
INSERT INTO 'informix'.question(question_id,question_text,status_id,keyword,question_type_id,question_style_id,is_required) VALUES (28430, 'Please enter your date of birth (yyyy/mm/dd)', 83, 'dob', 2, 4, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (313, 306, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (314, 306, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (324, 317, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (325, 317, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (331, 325, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (332, 325, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (337, 331, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (338, 331, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (347, 342, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (348, 342, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (355, 343, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (356, 343, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (357, 344, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (358, 344, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (340, 345, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (341, 345, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (349, 346, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (350, 346, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (386, 385, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (387, 385, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (400, 399, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (401, 399, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (409, 408, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (410, 408, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (416, 415, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (417, 415, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (434, 433, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (435, 433, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (452, 451, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (453, 451, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (462, 461, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (463, 461, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (476, 475, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (477, 475, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (484, 483, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (485, 483, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (491, 490, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (492, 490, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (500, 499, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (501, 499, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (511, 510, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (512, 510, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (521, 520, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (522, 520, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (532, 531, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (533, 531, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (548, 547, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (549, 547, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (556, 555, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (557, 555, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (568, 567, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (569, 567, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (581, 580, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (582, 580, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (589, 588, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (590, 588, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (609, 608, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (610, 608, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (621, 620, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (622, 620, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (631, 630, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (632, 630, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (638, 637, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (639, 637, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (649, 648, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (650, 648, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (657, 656, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (658, 656, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (665, 664, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (666, 664, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (674, 673, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (675, 673, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (685, 684, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (686, 684, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (699, 698, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (700, 698, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (702, 701, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (703, 701, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (713, 712, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (714, 712, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (722, 721, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (723, 721, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (732, 731, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (733, 731, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (739, 738, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (740, 738, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4123, 4122, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4124, 4122, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4141, 4140, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4142, 4140, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4147, 4146, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4148, 4146, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4166, 4165, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (4167, 4165, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (6021, 6020, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (6022, 6020, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7313, 7312, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7314, 7312, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7322, 7321, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7323, 7321, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7348, 7347, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7349, 7347, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7360, 7359, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7361, 7359, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7371, 7370, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7372, 7370, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7394, 7393, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7395, 7393, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7413, 7412, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7414, 7412, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7445, 7444, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7446, 7444, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7485, 7484, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7486, 7484, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7488, 7487, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7489, 7487, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7514, 7513, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7515, 7513, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7587, 7586, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7588, 7586, 'No', 2, 0);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7791, 7790, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7818, 7817, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7828, 7827, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7925, 7924, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7981, 7980, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7926, 7924, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (7982, 7980, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (8015, 8014, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (8016, 8014, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (8035, 8034, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (8036, 8034, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16261, 16260, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16262, 16260, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16330, 16329, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16331, 16329, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16333, 16332, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16334, 16332, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16336, 16335, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16337, 16335, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16341, 16340, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16342, 16340, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16346, 16345, 'Section A', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16347, 16345, 'Section B', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16348, 16345, 'Section C', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16350, 16349, 'Section A', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16351, 16349, 'Section B', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16352, 16349, 'Section C', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16354, 16353, 'Section A', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16355, 16353, 'Section B', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16356, 16353, 'Section C', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16371, 16370, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16372, 16370, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16649, 16648, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16650, 16648, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16671, 16670, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16672, 16670, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16914, 16913, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (16915, 16913, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17244, 17243, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17245, 17243, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17311, 17310, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17312, 17310, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17314, 17313, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17315, 17313, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17341, 17340, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17342, 17340, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17461, 17460, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (17462, 17460, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19031, 19030, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19032, 19030, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19121, 19120, 'Yes', 1, 1);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19122, 19120, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19259, 19258, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19260, 19258, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19262, 19261, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19263, 19261, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19265, 19264, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19266, 19264, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19268, 19267, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19269, 19267, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19274, 19273, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19275, 19273, 'No', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19413, 19412, 'Section A (Starts Feb 5, 9:00 PM EST)', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19414, 19412, 'Section B (Starts Feb 9, 1:00 PM EST)', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19415, 19412, 'Section C (Starts Feb 12, 7:00 AM EST)', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19417, 19416, 'Section A (Starts Feb 5, 9:00 PM EST)', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19418, 19416, 'Section B (Starts Feb 9, 1:00 PM EST)', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19419, 19416, 'Section C (Starts Feb 12, 7:00 AM EST)', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19421, 19420, 'Section A (Starts Feb 5, 9:00 PM EST)', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19422, 19420, 'Section B (Starts Feb 9, 1:00 PM EST)', 2, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (19423, 19420, 'Section C (Starts Feb 12, 7:00 AM EST)', 3, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (28433, 28432, 'Yes', 1, NULL);
INSERT INTO 'informix'.answer(answer_id,question_id,answer_text,sort_order,correct) VALUES (28434, 28432, 'No', 2, NULL);
INSERT INTO 'informix'.survey(survey_id,name,start_date,end_date,status_id,text,results_viewable) VALUES (19270, 'hsSeason2', '2007-07-12 00:00:00.000', '2008-03-16 00:00:00.000', 83, NULL, 0);
INSERT INTO 'informix'.survey(survey_id,name,start_date,end_date,status_id,text,results_viewable) VALUES (28429, 'hsSeason3', '2008-06-09 00:00:00.000', '2009-03-15 00:00:00.000', 83, NULL, 0);
INSERT INTO 'informix'.survey_question(survey_id,question_id) VALUES (19270, 19271);
INSERT INTO 'informix'.survey_question(survey_id,question_id) VALUES (19270, 19272);
INSERT INTO 'informix'.survey_question(survey_id,question_id) VALUES (19270, 19273);
INSERT INTO 'informix'.survey_question(survey_id,question_id) VALUES (28429, 28430);
INSERT INTO 'informix'.survey_question(survey_id,question_id) VALUES (28429, 28432);
INSERT INTO 'informix'.team(team_id,team_name,team_type,school_id,modify_date) VALUES (36023, 'Edmond North', NULL, 76406, '2008-09-22 16:02:17.000');
INSERT INTO 'informix'.team(team_id,team_name,team_type,school_id,modify_date) VALUES (36024, 'Downers Grove North', NULL, 76398, '2008-09-22 16:06:21.000');
INSERT INTO 'informix'.team_coder_xref(team_id,coder_id,captain,create_date) VALUES (36023, 27244066, NULL, '2008-09-22 16:02:17.000');
INSERT INTO 'informix'.team_coder_xref(team_id,coder_id,captain,create_date) VALUES (36024, 27244067, NULL, '2008-09-22 16:06:21.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244033, 0, 0, NULL, 0, 1, '2008-09-19 09:03:17.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244044, 0, 0, NULL, 0, 1, '2008-09-22 09:20:42.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244053, 0, 0, NULL, 0, 1, '2008-09-22 09:39:44.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244064, 0, 0, NULL, 0, 1, '2008-09-22 10:54:14.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244066, 0, 0, NULL, 0, 2, '2008-09-22 16:02:17.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244067, 0, 0, NULL, 0, 2, '2008-09-22 16:06:21.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244067, 0, 0, NULL, 0, 1, '2008-09-22 16:06:21.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244068, 0, 0, NULL, 0, 1, '2008-09-23 13:24:44.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244069, 0, 0, NULL, 0, 1, '2008-09-24 14:05:33.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244073, 0, 0, NULL, 0, 1, '2008-09-24 14:13:17.000');
INSERT INTO 'informix'.algo_rating(coder_id,rating,vol,round_id,num_ratings,algo_rating_type_id,modify_date) VALUES (27244093, 0, 0, NULL, 0, 1, '2008-09-24 14:49:37.000');
INSERT INTO 'informix'.season(season_id,start_date,end_date,name,season_type_id,event_id) VALUES (1, '2006-06-05 00:00:00.000', '2007-06-01 00:00:00.000', 'Season 1', 2, 990);
INSERT INTO 'informix'.season(season_id,start_date,end_date,name,season_type_id,event_id) VALUES (2, '2007-07-12 00:00:00.000', '2008-03-16 00:00:00.000', 'Season 2', 2, 991);
INSERT INTO 'informix'.season(season_id,start_date,end_date,name,season_type_id,event_id) VALUES (3, '2008-06-09 00:00:00.000', '2009-03-15 00:00:00.000', 'Season 3', 2, 993);
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593308, 27244066, 28430, NULL, NULL, '2008-09-22 16:02:17.000', '1992/03/04');
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593309, 27244066, 28432, 28433, NULL, '2008-09-22 16:02:17.000', NULL);
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593310, 27244067, 28430, NULL, NULL, '2008-09-22 16:06:21.000', '1992/04/05');
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593311, 27244067, 28432, 28433, NULL, '2008-09-22 16:06:21.000', NULL);
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593312, 27244068, 28432, 28434, NULL, '2008-09-23 13:24:45.000', NULL);
INSERT INTO 'informix'.response(response_id,user_id,question_id,answer_id,response_text,create_date,response) VALUES (593313, 27244068, 28430, NULL, NULL, '2008-09-23 13:24:45.000', '1976/05/12');
INSERT INTO 'informix'.event (event_id,event_type_id,event_desc,start_registration,end_registration,terms_of_use_id,survey_id,event_short_desc,modify_date,parent_event_id) VALUES (991, 14, "High School Season 2", "2007-05-25 00:00:00.000", "2008-03-16 00:00:00.000", null, 19270, "hsseason2", "2007-07-18 11:05:17.000", null);
INSERT INTO 'informix'.event (event_id,event_type_id,event_desc,start_registration,end_registration,terms_of_use_id,survey_id,event_short_desc,modify_date,parent_event_id) VALUES (993, 14, "High School Season 3", "2008-05-09 00:00:00.000", "2008-09-01 00:00:00.000", null, 28429, "hsseason3", "2008-06-26 15:00:34.000", null);
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (-1,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (1,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (2,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (3,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (10,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (11,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (13,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (14,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (20,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (30,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (31,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (32,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (33,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (34,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (40,'G');
INSERT INTO 'informix'.secure_object (secure_object_id,secure_object_type) VALUES (50,'G');
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (-1,'Contest Defualt Group All Access',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (1,'Executive',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (2,'Manager',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (3,'Developer',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (10,'Coders',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (11,'JobPostings',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (13,'Level One Admins',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (14,'Level Two Admins',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (20,'Subscribers',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (30,'writer',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (31,'tester',null);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (40,'College Student',10);
INSERT INTO 'informix'.group (group_id,group_desc,access_id) VALUES (50,'Admin Monitor Contest-Round Administration',10);
INSERT INTO 'informix'.round (round_id,contest_id,name,status,ran_ratings,paid_money,registration_limit,notes,invitational,round_type_id) VALUES (0,null,'lobby round',null,null,null,null,null,null,null);
INSERT INTO 'informix'.room (room_id,round_id,name,state_code,country_code,region_code,division_id,room_type_id,eligible,unrated,room_limit) VALUES (0,0,'Admin Lobby Room',null,null,null,null,5,null,null,-1);
INSERT INTO 'informix'.room (room_id,round_id,name,state_code,country_code,region_code,division_id,room_type_id,eligible,unrated,room_limit) VALUES (11,0,'Chat Room 1',null,null,null,null,5,null,null,999);
INSERT INTO 'informix'.room (room_id,round_id,name,state_code,country_code,region_code,division_id,room_type_id,eligible,unrated,room_limit) VALUES (12,0,'Chat Room 2',null,null,null,null,5,null,null,999);
INSERT INTO 'informix'.group_user VALUES (10,132456);
INSERT INTO 'informix'.group_user VALUES (10,20);
INSERT INTO 'informix'.group_user VALUES (10,21);
INSERT INTO 'informix'.group_user VALUES (10,132457);
INSERT INTO 'informix'.group_user VALUES (10,132458);
INSERT INTO 'informix'.group_user VALUES (10,124764);
INSERT INTO 'informix'.group_user VALUES (10,124772);
INSERT INTO 'informix'.group_user VALUES (10,124766);
INSERT INTO 'informix'.group_user VALUES (10,124776);
INSERT INTO 'informix'.group_user VALUES (10,124834);
INSERT INTO 'informix'.group_user VALUES (10,124835);
INSERT INTO 'informix'.group_user VALUES (10,124836);
INSERT INTO 'informix'.group_user VALUES (10,124852);
INSERT INTO 'informix'.group_user VALUES (10,124853);
INSERT INTO 'informix'.group_user VALUES (10,124856);
INSERT INTO 'informix'.group_user VALUES (10,124857);
INSERT INTO 'informix'.group_user VALUES (10,124861);
INSERT INTO 'informix'.group_user VALUES (10,124916);
INSERT INTO 'informix'.group_user VALUES (10,22770213);
INSERT INTO 'informix'.group_user VALUES (10,22719217);
INSERT INTO 'informix'.group_user VALUES (10,22719218);
INSERT INTO 'informix'.group_user VALUES (10,22873364);
INSERT INTO 'informix'.group_user VALUES (13,132456);
INSERT INTO 'informix'.group_user VALUES (13,132457);
INSERT INTO 'informix'.group_user VALUES (14,132456);
INSERT INTO 'informix'.group_user VALUES (14,132457);
INSERT INTO 'informix'.group_user VALUES (30,124776);
INSERT INTO 'informix'.group_user VALUES (30,124834);
INSERT INTO 'informix'.group_user VALUES (31,124776);
INSERT INTO 'informix'.group_user VALUES (31,124834);
INSERT INTO 'informix'.generic_counter_client VALUES (1, 'LongContestServices#Test');

INSERT INTO 'informix'.tax_form(name, tax_form_id, text, status_id, tax_form_desc, default_withholding_amount, default_withholding_percentage, use_percentage) VALUES ("w-9", 1, null, 62, "US Tax Form", 0, 0, 1);
INSERT INTO 'informix'.tax_form(name, tax_form_id, text, status_id, tax_form_desc, default_withholding_amount, default_withholding_percentage, use_percentage) VALUES ("W-8BEN", 2, null, 62, "Foreign Tax Form", 0, 0.3, 1);